# Welcome to Jekyll!
#
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PHD SRG.
subtitle: Research
email: sergiorgiraldo@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   PHD journey for Sergio Giraldo.
baseurl: "/phd" 
url: "https://sergiorgiraldo.github.io" 
twitter_username: sergiorgiraldo
github_username:  sergiorgiraldo
author: Sergio Giraldo
permalink: /:year/:month/:day/:title:output_ext
paginate: 5
markdown: kramdown

theme: jekyll-theme-superb
plugins:
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-sitemap