# Welcome to Jekyll!
#
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PHD SRG
# email: sergiorgiraldo@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   PHD journey for Sergio Giraldo.
baseurl: "/phd" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sergiorgiraldo
github_username:  sergiorgiraldo
author: Sergio Giraldo
paginate: 5

# Build settings
theme: minima #https://github.com/jekyll/minima/tree/master
plugins:
  - jekyll-paginate

minima:
  social_links:
   - { platform: github, title: "/sergiorgiraldo", user_url: "https://github.com/sergiorgiraldo" }
   - { platform: twitter, title: "/sergiorgiraldo", user_url: "https://twitter.com/sergiorgiraldo" }
   - { platform: linkedin, title: "/sergiorgiraldo", user_url: "https://www.linkedin.com/in/sergiorgiraldo" }