source "https://rubygems.org"

gem "minima", "~> 2.5"
gem "jekyll-paginate", "~> 1.1"
gem "github-pages", "~> 231", group: :jekyll_plugins
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
