source "https://rubygems.org"

gem "jekyll", "= 3.9.5"
gem "minima", "~> 2.5"
gem "github-pages", "~> 231", group: :jekyll_plugins
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "webrick", "~> 1.8"

gem "jekyll-paginate", "~> 1.1"

group :jekyll_plugins do
    gem "jekyll-category-pages", "~> 1.0.1"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end